version: 2
updates:
  - package-ecosystem: 'npm'
    rebase-strategy: auto
    target-branch: 'next'
    open-pull-requests-limit: 8
    directory: '/'
    schedule:
      interval: 'daily'
    reviewers:
      - 'MM25Zamanian'
    assignees:
      - 'MM25Zamanian'
    labels:
      - 'enhancement'
