root: true

extends:
  - eslint:recommended
  - google
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:wc/recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - '@open-wc/eslint-config'

env:
  browser: true
  es2021: true

parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2021
  sourceType: module

plugins:
  - '@typescript-eslint'
  - import
  - wc
  - prettier

settings:
  import/resolver:
    typescript:
      alwaysTryTypes: true
      project: 'package/*/tsconfig.json'
  wc:
    elementBaseClasses:
      - LitElement
      # TODO: Add other classes

rules:
  array-callback-return: off
  brace-style: error
  arrow-body-style:
    - error
    - always
  implicit-arrow-linebreak:
    - error
    - beside
  arrow-parens:
    - error
    - always
  no-unused-vars:
    - error
    - vars: local
      args: none
  indent: off
  object-curly-spacing:
    - error
    - never
  max-len:
    - error
    - code: 120
  no-eval:
    - error
    - allowIndirect: true
  no-floating-decimal: error
  space-infix-ops: error
  new-cap:
    - error
    - capIsNewExceptionPattern: 'Mixin$'
  '@typescript-eslint/explicit-function-return-type': error
  'import/order':
    - error
    - groups:
        - 'builtin'
        - 'external'
        - 'internal'
        - - 'parent'
          - 'sibling'
          - 'index'
        - 'type'
      'newlines-between': 'always'
      alphabetize:
        order: asc
        caseInsensitive: true

  # TODO: Enable in future
  import/no-unresolved: off
  wc/guard-super-call: off
  class-methods-use-this: off
  import/extensions: off
  require-jsdoc: off
  valid-jsdoc: off
