root: true

ignorePatterns:
  - .gitignore

extends:
  - eslint:recommended
  - google
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:wc/best-practice
  - plugin:lit/recommended

env:
  browser: true
  es2021: true

parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2021
  sourceType: module

plugins:
  - '@typescript-eslint'
  - import
  - wc

settings:
  import/resolver:
    typescript:
      alwaysTryTypes: true

rules:
  import/no-unresolved: off
  require-jsdoc: off
  valid-jsdoc: off
