extends:
  - stylelint-config-standard

overrides:
  - files:
      - '**/*.html'
    customSyntax: 'postcss-html'
  - files:
      - '**/*.ts'
    customSyntax: 'postcss-lit'

ignoreFiles: .gitignore
